### ISSUE TITLE
Convert DOC to DOCX fails

### ISSUE THREAD

**Issue by zsleo01** [tobya/DocTo#186]
converting a DOC to DOCX fails. I have the latest version of Office installed

Here is the console output.

D:\apps\Test>docto -f "d:\temp\docs\Automating Office.doc" -O "D:\temp\docs\Automating Office.docx" -T wdFormatOpenDocumentText
[INFO]   FileToConvert:d:\temp\docs\Automating Office.doc
[INFO]   OutputFile:D:\temp\docs\Automating Office.docx
[INFO]   Ext23
*******************************************
Error: EOleException  Incompatible file type and file extension-- (D:\temp\docs\Automating Office.docx)
*******************************************
*******************************************
Error: Exiting with Error Code : 220
*******************************************

**Comment by tobya** [comment]
I'm unsure but this maybe because you have chosen the wrong file type for docx.

Perhpas try this 

> docto -WD -f "C:\Folder\With\OldFile.doc" -O "C:\Folder\For\NewFile.docx"  -T wdFormatDocumentDefault -C 65535

The `-c` is important as this tells word to save with the hightest compatibilyt for the version of word you have. 

Otherwise try wdFormatStrictOpenXMLDocument might be an option.

I've never seen that error before so I'll try and find out more.

Let me know if you solve the issue with the above ideas.

**Comment by tobya** [comment]
Actually as per https://stackoverflow.com/questions/39166746/word-vba-saveas-error-incompatible-file-type-and-file-extension

There is a suggestion that docx is actually wdFormatXMLDocument  so perhaps try that also
