### ISSUE TITLE
the process pause in the middle,

### ISSUE THREAD

**Issue by zhanglianbo35** [tobya/DocTo#63]
if there are many files need to be converted(some files may be larger than 50M ), it seems the process will be easily paused in the middle,(not compute issue) the environment is WIN10 64 bit, and MS office 2016 32 bit.

**Comment by tobya** [comment]
By pause do you mean stop and hang?

Usually this is because 1 document has caused Word to pop up a dialog or a system error. Try the latest build it has some fixes. Otherwise if you can figure out which document causes the hang if you can send it to me I can see if I can figure out what is happening

**Comment by zhanglianbo35** [comment]
I tested it several times,  I found in WIN10 and office 2016, if the RTF file is very large(larger than 50M) then the task will be hang,  there is no error,  But in Win7 and office 2013,  although the task will be very slow, when met large file,  it finally can be finished.

**Comment by tobya** [comment]
The reality here is that it is Word that is saving the file as a pdf.  Does the file save successfully as a pdf if you try manually from word?

**Comment by zhanglianbo35** [comment]
Yes, it can be saved as PDF manually successfully in MS WORD.
